### ISSUE TITLE
OES_texture_float is missing on Android.

### ISSUE THREAD

**Issue by imokya** [yomboprime/GPGPU-threejs-demos#8]
OES_texture_float is missing on Android. Is it possilbe to make GPUComputation android compatible?

**Comment by yomboprime** [comment]
Hello,

This repository was merged with the Three.js official one.

Please see [this issue](https://github.com/mrdoob/three.js/issues/9628), I think it is already solved there by using ```HalfFloat```

Thanks

**Comment by imokya** [comment]
hi @yomboprime
Thanks for your response.It fails to work on android browser, fine on ios device.

**Comment by yomboprime** [comment]
> hi @yomboprime
> Thanks for your response.It fails to work on android browser, fine on ios device.

Then, please consider opening a new issue in the Three.js repo, about the bug on Android.
